//do{
//code
//}
//while(condition;)

/*let i=1
do{
    console.log(i)
    i++
}
while(i<=10)*/

    /*let k=50
    do{
        console.log(k)
        k++
    }
    while(k<=60)*/

        /*let j=2, 
        do
        {
            console.log(j)
            
            j=j+2
        }
while(j<=10)*/

    let sum=0 ,k=2
    do{
        
        sum=sum+k
        k=k+2
    }
    while(k<=10)
        console.log(sum)